# I/O
input_directory: ../input/PORTA/
input_file:      cai_0Bx_0By_0Bz_1Vx_1Vy_1Vz_GT4_5x5x133_it100.pmd
frequency_file:  frequency/96F/frequency.dat

output: false
output_overwrite_prevention: false
output_directory: /gpfs/projects/ehpc238/output

use_B: true
use_continuum: false
formal_solver: BESSER

emissivity_model: PRD_AA

# used only for FAL-C input
N_theta: 8
N_chi:   16

input_cul_string:  ""
input_qel_string:  ""
input_llp_string:  ""
input_back_string: ""

use_prec: true

solver:
  ksp_solver_type: KSPFGMRES
  ksp_rtol: 1e-4
  ksp_max_it: 1000

prec:
  pc_solver_type: KSPGMRES
  pc_rtol: 1e-4
  pc_max_it: 1000
